language: php
php:
  - 5.6

before_script:
  - composer install --no-interaction

notifications:
  slack:
    secure: jU9WRRWKjSxVnCL4X4CR/3LSFIJU+nOpiDyVhRyq0QF6q99U5UUj8nm8KP6w4bPnMORfuBUVqzXhDdNwfYipOLpRUB0xmJk/qzaT8MB8MAgBbqnMfIszuG59FZJbsfPT+Xe37Nbe1m0nX/1u3XAxWafgAiLA4zH2jLzC2FrSKgnTWX+bY95YRZfihSvpnSf+CTjsmrf687L3LhlrcYf/Fn6XjwHkdtS8WieAE6aSzdJ9IHepnEM9Bfi3era2QvX/fdUNLCM4rTkTDW7nlvU5zFLRSPEy5CIgqBnQqbki8JcjUnVkn64Z/lu4XbgYlq1WZyHG8TUOHYV0HzAwDZoTtOi3vvQ3BpDyb0DrtMGNkIjSeDPBk1HRsxcw2t0ih5r8cE0KMSUokKiJRi9ALv1fXgJGZAtDzYIYzHg8VcgbpclFfURpOSzQEpRo6UcZDfhK0jpSeUiv2SKm+EmLICVlOqYoSR1y5KZZKNEhXvSKZUnyALTA251RfiI//XoUb9xuT28CiOEPVSgtzi9m1ZrohuLPWYDVUlpDH4tga95Q0614xq97FYIXK6SM10wh7vDrxKq3YMd4R7rFQqf5tPsCSSEbk0NaRBNP0sIy0R1zG0/yRx6yHRKuBwe59sfN+/wnxfjeUJyuoz/b53YTg6//bxv/EIgGYx6WQHi88k/xNNU=

before_deploy:
  - rm -rf node_modules/
  - zip -qr ../MuhitAPP-${TRAVIS_BUILD_NUMBER}.zip ./*
  - mv ../MuhitAPP-${TRAVIS_BUILD_NUMBER}.zip ${TRAVIS_BUILD_DIR}/
