language: php
php:
  - 5.6

before_script:
  - composer install --no-interaction

notifications:
  slack:
    secure: jU9WRRWKjSxVnCL4X4CR/3LSFIJU+nOpiDyVhRyq0QF6q99U5UUj8nm8KP6w4bPnMORfuBUVqzXhDdNwfYipOLpRUB0xmJk/qzaT8MB8MAgBbqnMfIszuG59FZJbsfPT+Xe37Nbe1m0nX/1u3XAxWafgAiLA4zH2jLzC2FrSKgnTWX+bY95YRZfihSvpnSf+CTjsmrf687L3LhlrcYf/Fn6XjwHkdtS8WieAE6aSzdJ9IHepnEM9Bfi3era2QvX/fdUNLCM4rTkTDW7nlvU5zFLRSPEy5CIgqBnQqbki8JcjUnVkn64Z/lu4XbgYlq1WZyHG8TUOHYV0HzAwDZoTtOi3vvQ3BpDyb0DrtMGNkIjSeDPBk1HRsxcw2t0ih5r8cE0KMSUokKiJRi9ALv1fXgJGZAtDzYIYzHg8VcgbpclFfURpOSzQEpRo6UcZDfhK0jpSeUiv2SKm+EmLICVlOqYoSR1y5KZZKNEhXvSKZUnyALTA251RfiI//XoUb9xuT28CiOEPVSgtzi9m1ZrohuLPWYDVUlpDH4tga95Q0614xq97FYIXK6SM10wh7vDrxKq3YMd4R7rFQqf5tPsCSSEbk0NaRBNP0sIy0R1zG0/yRx6yHRKuBwe59sfN+/wnxfjeUJyuoz/b53YTg6//bxv/EIgGYx6WQHi88k/xNNU=

before_deploy:
  - zip ../MuhitAPP-stage-${TRAVIS_BUILD_NUMBER}-${TRAVIS_COMMIT}.zip ./*
  - mv ../MuhitAPP-stage-${TRAVIS_BUILD_NUMBER}-${TRAVIS_COMMIT}.zip ${TRAVIS_BUILD_DIR}/

deploy:
  - provider: elasticbeanstalk
    skip_cleanup: true
    zip_file: MuhitAPP-stage-${TRAVIS_BUILD_NUMBER}-${TRAVIS_COMMIT}.zip
    access_key_id: 
      secure: QQYc+cdhycjmxInCd1qCNeUQptZyJPAjHl5tAY6b54YuhWIzJapnXrWWeL0snebelzRvi82vk+Tc7YcK0zIzsXM62/K4OUqAlsfAnih5cnm234w9EYfcHOzJY2fFcrgbLkWRKXWXTB3YhcT4/N6W0KwGUYhpiOgD0cZ+Sez5iwAJO4XPP/z0G8ellFhsH3UJrsi/iULPTPA6Spp44tTd9k4uLrd86A+28GsKLjVjQ52xbTlC3BHxmozTC5u0j9Z5KwNDqRMLrEgiXA23Oni8Bl5WO+0177NEtGU7SeJP0cifHg21RQYMMZ//3CbK/WooeVn+LrpiRUzdx7Kkd4g3IqAn5V7p/A7u9vvWuzwSgLx8qymp9EncNP4WV9rus5zhaE08hQqO+nZoebPR+vpVrFj/zieU94jjCNUxrPiqvvc066Qidxjfw/AaeMf6A9Y1tDOWBs5dSZshG9Wpu+ch1IWTvFLhLrMByqEt5kMh2s2zyiUqLSeyrwnBOWHr/PKBx/BJXGVy2K/7up1xjefzbCWbSU4F/U8wEtLocGoleL07qoU6AOnrKllO7TtOGvhoEcclFgnjg/AdJdKlqsehzSSBRQdWUKucIegsuE6WeDqoTlrPiLZ8Kqjn2K4wxEk/WCFtNu+DUaXS9hluU+BVNPSJezG3fIophh4KbanDP1A=
    secret_access_key:
      secure: W5vrvCmHyKLft7ALl2Obi3RhYgBHdgpHhJ7DwwLvBbtvnZ2rTcsvhVlpAC3vftvG1cjyycf0DEpzLU6JeuWxgy7GBpSGM8o96fhnhfdIEy0DnJ5W7LI65Uk/LP1BZsHijZVVUa02FxK2g1SyzgHcwUJWBLZ8Y5PpMfHTaFf88e3CfQijKZxfDUpU5UMsv9YCKpuCeor6vBDSavl9ijSL4nXSON4Ls3aPYg/AHN+tH50DD2nP/3iRw6XoN3FTnyR5xa3dsPmx5l/meI94tagP1pyo/C3+zuGyCmsIzEvKslnFIqExDZJKhSRFt76/bJ5fuGV/K0x/ikLQWgImgsAV7Anxh3FXU4yjielzjZN0CaUWdL6orqKJs4NSyxhL2Tp71FG5IZHIscCyo634O7CIeLZ7r6YNPMvSsXvIOPAPzqdsyDgJ8yPNKQ4rVYNq+SGqPo4Ex4HZ0wDPv1t9Q4p2BdkKJ1TbBI6Vp4hrMcwntRF1jKdoWVbOBTivrGodffhgB411OeHZKTvfPm3sgPttjnUq1OR4aHcjOm7LqIGBkNpN202R64OcBNFN25iWYH1JtCFDrexxiDcgCIuf2kAehVSe0Wfp7hRqF0UKIWyfv8s2mEq1YWMhrKs5a/5XkiyPSPzuUo5wl/osyavBHF3ZOCo2ot2msmA8EGuEcKPVLUw=
    region: eu-west-1
    app: 
      secure: LBezfVKi8ZOVae10OEVdjNNp7sM3qQcDKm7R+BPkwdqMK4TqgE1sdQVpBQw8F/2hIB7Eo7zI6HJKfoNqZfgtB9OMQjq2/wQYhMziJGNAe8n6fcuxXcHTv1vFpLk0LRDz3HXSKZQiGibw1pKAziZQHq/qqTrSZQzOHWoEHAzDI9J8H+hY0+Gb+RI/veN+0MyyOxDbD7TZkd4ByEJb1GlajIy0/DAZhvzd5jqyl1jODhV9VK5+JJNY+bUdjKQrSBopMZgEE8xSxvvQOcelgcMof9CqhwF921LsL9i7cgQNE7CeOeTbV3CDY8hOGlOwafZJGb4CZmLEXQVnfjBI2FcIpXCvFTVMIPJqEpywuWRCq4gB0KGw1IOEjRlfL/1kbgI3Bjsi/p1POeKL7Krm4DZE6p4hysx3zZLGDxIBswrzH4Gq5f8pw0xAJkxq6f3fQa5D/KBK7K9QI+v7+rbX6ezt7IHDDnIj1xxpdiKSDgkZc+4VjAGjaUWu/DBfff+bjpslQy9XcZ/ujZ8muHTbZOiuqpjw38zx3HVo/SQqRo435Bq1GHI4uSvS5ryaYAl3Obbgj6zKZNRzRA1EeRTEGcJYUDKpmuzKq0ZkoL8Fu6XjTV8z8UzHItjKrPPI7I5tDRA4m0MaDjYp5uuV8md9Ii9+ebsJDPb4yD7Lw8ghySo8AKQ=
    env: app-stage
    bucket_name: muhit-travis-ci 
    on:
      repo: Muhit-co/api
      branch: feature/*
