language: php
php:
- 5.6
before_script:
- composer install --no-interaction
notifications:
  slack:
    secure: jU9WRRWKjSxVnCL4X4CR/3LSFIJU+nOpiDyVhRyq0QF6q99U5UUj8nm8KP6w4bPnMORfuBUVqzXhDdNwfYipOLpRUB0xmJk/qzaT8MB8MAgBbqnMfIszuG59FZJbsfPT+Xe37Nbe1m0nX/1u3XAxWafgAiLA4zH2jLzC2FrSKgnTWX+bY95YRZfihSvpnSf+CTjsmrf687L3LhlrcYf/Fn6XjwHkdtS8WieAE6aSzdJ9IHepnEM9Bfi3era2QvX/fdUNLCM4rTkTDW7nlvU5zFLRSPEy5CIgqBnQqbki8JcjUnVkn64Z/lu4XbgYlq1WZyHG8TUOHYV0HzAwDZoTtOi3vvQ3BpDyb0DrtMGNkIjSeDPBk1HRsxcw2t0ih5r8cE0KMSUokKiJRi9ALv1fXgJGZAtDzYIYzHg8VcgbpclFfURpOSzQEpRo6UcZDfhK0jpSeUiv2SKm+EmLICVlOqYoSR1y5KZZKNEhXvSKZUnyALTA251RfiI//XoUb9xuT28CiOEPVSgtzi9m1ZrohuLPWYDVUlpDH4tga95Q0614xq97FYIXK6SM10wh7vDrxKq3YMd4R7rFQqf5tPsCSSEbk0NaRBNP0sIy0R1zG0/yRx6yHRKuBwe59sfN+/wnxfjeUJyuoz/b53YTg6//bxv/EIgGYx6WQHi88k/xNNU=
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAU7ABCZ74YPXUUHOL
  secret_access_key:
    secure: W5vrvCmHyKLft7ALl2Obi3RhYgBHdgpHhJ7DwwLvBbtvnZ2rTcsvhVlpAC3vftvG1cjyycf0DEpzLU6JeuWxgy7GBpSGM8o96fhnhfdIEy0DnJ5W7LI65Uk/LP1BZsHijZVVUa02FxK2g1SyzgHcwUJWBLZ8Y5PpMfHTaFf88e3CfQijKZxfDUpU5UMsv9YCKpuCeor6vBDSavl9ijSL4nXSON4Ls3aPYg/AHN+tH50DD2nP/3iRw6XoN3FTnyR5xa3dsPmx5l/meI94tagP1pyo/C3+zuGyCmsIzEvKslnFIqExDZJKhSRFt76/bJ5fuGV/K0x/ikLQWgImgsAV7Anxh3FXU4yjielzjZN0CaUWdL6orqKJs4NSyxhL2Tp71FG5IZHIscCyo634O7CIeLZ7r6YNPMvSsXvIOPAPzqdsyDgJ8yPNKQ4rVYNq+SGqPo4Ex4HZ0wDPv1t9Q4p2BdkKJ1TbBI6Vp4hrMcwntRF1jKdoWVbOBTivrGodffhgB411OeHZKTvfPm3sgPttjnUq1OR4aHcjOm7LqIGBkNpN202R64OcBNFN25iWYH1JtCFDrexxiDcgCIuf2kAehVSe0Wfp7hRqF0UKIWyfv8s2mEq1YWMhrKs5a/5XkiyPSPzuUo5wl/osyavBHF3ZOCo2ot2msmA8EGuEcKPVLUw=
  region: eu-west-1
  app: api
  env: app-stage
  on:
    repo: Muhit-co/api
    branch: feature/*
